servers:
  lobby1:
    address: 192.168.0.50:19133
  lobby2:
    address: 192.168.0.50:19134
listener:
  motd: "§bWaterdog§3PE"
  priorities:
    - lobby1
  host: 192.168.0.50:19132
  max_players: 20
  force_default_server: false
  forced_hosts:
    pvp.waterdog.io: pvp

online_mode: true

ip_forward: false
replace_username_spaces: true
network_compression_threshold: 256
